using RestaurantMenu.Models;

namespace RestaurantMenu.ViewModels;

/// <summary>Branch/Print: table tents or sticker sheets with a QR code per table.</summary>
public class PrintViewModel
{
    public const string Tent = "tent";
    public const string Sticker = "sticker";

    /// <summary>Most cards one print run renders (a 200-table restaurant is 100 A4 pages of tents).</summary>
    public const int MaxCards = 200;

    public required Branch Branch { get; init; }

    /// <summary><see cref="Tent"/>: two A6 folding tents per A4 page. <see cref="Sticker"/>: twelve stickers per A4 page.</summary>
    public required string Layout { get; init; }

    public int From { get; init; }
    public int To { get; init; }

    /// <summary>One code for the whole menu, without a table number (window, counter, flyers).</summary>
    public bool NoTables { get; init; }
    public int Copies { get; init; }

    public required string Language { get; init; }
    public required string[] Languages { get; init; }
    public required string Headline { get; init; }

    /// <summary>The menu address printed under the code, without the scheme, for guests who can't scan.</summary>
    public required string ShortUrl { get; init; }
    public required string BrandColor { get; init; }

    /// <summary>Set when the requested range had to be corrected.</summary>
    public string? Notice { get; init; }

    public required IReadOnlyList<PrintCard> Cards { get; init; }

    public int PerPage => Layout == Tent ? 2 : 12;
}

/// <param name="Table">Null for a whole-menu code.</param>
/// <param name="Svg">Inline SVG markup generated by QrCodeService (no user input).</param>
public record PrintCard(int? Table, string? TableLabel, string Svg, string Url);
