-- =============================================================================
-- One-time production upgrade for My Quick Menu (run BEFORE deploying this version)
--
-- Why: the old EF migrations were generated for SQL Server and never matched the
-- Postgres database. They were replaced by a clean Postgres baseline
-- (20261003181758_InitialPostgres) that matches the schema production already has.
-- This script:
--   1. records that baseline as applied, without touching any table;
--   2. applies the new SoftDeleteMenus migration (categories and dishes become
--      soft-deletable; branch names unique among live branches only).
-- It is safe to run more than once.
--
-- Run it with:  psql "$PROD_DATABASE_URL" -v ON_ERROR_STOP=1 -f prod-upgrade.sql
-- (Render: Dashboard > your Postgres > Connect > External connection string)
-- Take a backup first: Render > Postgres > Backups, or pg_dump.
-- =============================================================================

BEGIN;

-- 1. Baseline -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Old SQL Server migration records, if any were ever written.
DELETE FROM "__EFMigrationsHistory"
WHERE "MigrationId" IN (
    '20260104225112_InitialCreate',
    '20260104230849_Admin',
    '20260104235347_AddCurrencyToBranch',
    '20260105222447_AddMultiLanguageAndThemeSupport'
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261003181758_InitialPostgres', '8.0.22')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;

-- 2. Everything after the baseline (generated by: dotnet ef migrations script InitialPostgres --idempotent)
START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003181828_SoftDeleteMenus') THEN
    DROP INDEX IF EXISTS "IX_Branches_Name";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003181828_SoftDeleteMenus') THEN
    ALTER TABLE "Products" ADD "DeletedOnUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003181828_SoftDeleteMenus') THEN
    ALTER TABLE "Products" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003181828_SoftDeleteMenus') THEN
    ALTER TABLE "Categories" ADD "DeletedOnUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003181828_SoftDeleteMenus') THEN
    ALTER TABLE "Categories" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003181828_SoftDeleteMenus') THEN
    CREATE UNIQUE INDEX "IX_Branches_Name" ON "Branches" ("Name") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003181828_SoftDeleteMenus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003181828_SoftDeleteMenus', '8.0.22');
    END IF;
END $EF$;
COMMIT;

